### ISSUE TITLE
ESC key is not giving you realtek prompt

### ISSUE THREAD

**Issue by ersinpw** [parasite85/tuya_dmd2cc_gateway_hack#1]
I have the problem that ESC key is not giving the realtek prompt. Therefore, I tried the method which is supposed in the tutorial. However, I encounter the problem that after I get the `<RealTek>` prompt, the serial doesn't react to any key input. Is this correct? I tried several times to send the following:

    FLR 80000000 401802 16
    DW 80000000 4

However, I don't get any response back.

This is my full output for so far:

    Booting...
    
    @@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@
    @
    @ chip__no chip__id mfr___id dev___id cap___id size_sft dev_size chipSize
    @ 0000000h 0XXXXXXh 0000XXXh 0000040h 0000018h 0000000h 0000018h 1000000h
    @ blk_size blk__cnt sec_size sec__cnt pageSize page_cnt chip_clk chipName
    @ 0010000h 0000100h 0001000h 0001000h 0000100h 0000010h 000004eh GD25Q128
    @ 
    @@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@
    DDR1:32MB
     
    ---RealTek(RTL8196E)at 2021.07.29-21:33+0800 v3.4T-pre2 [16bit](380MHz)
    P0phymode=01, embedded phy
    check_image_header  return_addr:05010000 bank_offset:00000000
    no sys signature at 00010000!
    rootfs checksum error at 00200000!
    no rootfs signature at 00210000!
    no rootfs signature at 00250000!
    no rootfs signature at 00201000!
    no rootfs signature at 00202000!
    no rootfs signature at 00203000!
    no rootfs signature at 00204000!
    no rootfs signature at 00205000!
    no rootfs signature at 00206000!
    no rootfs signature at 00207000!
    no rootfs signature at 00208000!
    no rootfs signature at 00209000!
    no rootfs signature at 0020A000!
    no rootfs signature at 0020B000!
    no rootfs signature at 0020C000!
    no rootfs signature at 0020D000!
    no rootfs signature at 0020E000!
    no rootfs signature at 0020F000!
    no rootfs signature at 00211000!
    no rootfs signature at 00212000!
    no rootfs signature at 00213000!
    no rootfs signature at 00214000!
    no rootfs signature at 00215000!
    no rootfs signature at 00216000!
    no rootfs signature at 00217000!
    no rootfs signature at 00218000!
    no rootfs signature at 00219000!
    no rootfs signature at 0021A000!
    no rootfs signature at 0021B000!
    no rootfs signature at 0021C000!
    no rootfs signature at 0021D000!
    no rootfs signature at 0021E000!
    no rootfs signature at 0021F000!
    no rootfs signature at 00220000!
    no rootfs signature at 00221000!
    no rootfs signature at 00222000!
    no rootfs signature at 00223000!
    no rootfs signature at 00224000!
    no rootfs signature at 00225000!
    no rootfs signature at 00226000!
    no rootfs signature at 00227000!
    no rootfs signature at 00228000!
    no rootfs signature at 00229000!
    no rootfs signature at 0022A000!
    no rootfs signature at 0022B000!
    no rootfs signature at 0022C000!
    no rootfs signature at 0022D000!
    no rootfs signature at 0022E000!
    no rootfs signature at 0022F000!
    no rootfs signature at 00230000!
    no rootfs signature at 00231000!
    no rootfs signature at 00232000!
    no rootfs signature at 00233000!
    no rootfs signature at 00234000!
    no rootfs signature at 00235000!
    no rootfs signature at 00236000!
    no rootfs signature at 00237000!
    no rootfs signature at 00238000!
    no rootfs signature at 00239000!
    no rootfs signature at 0023A000!
    no rootfs signature at 0023B000!
    no rootfs signature at 0023C000!
    no rootfs signature at 0023D000!
    no rootfs signature at 0023E000!
    no rootfs signature at 0023F000!
    no rootfs signature at 00240000!
    no rootfs signature at 00241000!
    no rootfs signature at 00242000!
    no rootfs signature at 00243000!
    no rootfs signature at 00244000!
    no rootfs signature at 00245000!
    no rootfs signature at 00246000!
    no rootfs signature at 00247000!
    no rootfs signature at 00248000!
    no rootfs signature at 00249000!
    no rootfs signature at 0024A000!
    no rootfs signature at 0024B000!
    no rootfs signature at 0024C000!
    no rootfs signature at 0024D000!
    no rootfs signature at 0024E000!
    no rootfs signature at 0024F000!
    no rootfs signature at 00251000!
    no rootfs signature at 00252000!
    no rootfs signature at 00253000!
    no rootfs signature at 00254000!
    no rootfs signature at 00255000!
    no rootfs signature at 00256000!
    no rootfs signature at 00257000!
    no rootfs signature at 00258000!
    no rootfs signature at 00259000!
    no rootfs signature at 0025A000!
    no rootfs signature at 0025B000!
    no rootfs signature at 0025C000!
    no rootfs signature at 0025D000!
    no rootfs signature at 0025E000!
    no rootfs signature at 0025F000!
    no rootfs signature at 00260000!
    no rootfs signature at 00261000!
    no rootfs signature at 00262000!
    no rootfs signature at 00263000!
    no rootfs signature at 00264000!
    no rootfs signature at 00265000!
    no rootfs signature at 00266000!
    no rootfs signature at 00267000!
    no rootfs signature at 00268000!
    no rootfs signature at 00269000!
    no rootfs signature at 0026A000!
    no rootfs signature at 0026B000!
    no rootfs signature at 0026C000!
    no rootfs signature at 0026D000!
    no rootfs signature at 0026E000!
    no rootfs signature at 0026F000!
    no rootfs signature at 00270000!
    no rootfs signature at 00271000!
    no rootfs signature at 00272000!
    no rootfs signature at 00273000!
    no rootfs signature at 00274000!
    no rootfs signature at 00275000!
    no rootfs signature at 00276000!
    no rootfs signature at 00277000!
    no rootfs signature at 00278000!
    no rootfs signature at 00279000!
    no rootfs signature at 0027A000!
    no rootfs signature at 0027B000!
    no rootfs signature at 0027C000!
    no rootfs signature at 0027D000!
    no rootfs signature at 0027E000!
    no rootfs signature at 0027F000!
    no rootfs signature at 00280000!
    no rootfs signature at 00281000!
    no rootfs signature at 00282000!
    no rootfs signature at 00283000!
    no rootfs signature at 00284000!
    no rootfs signature at 00285000!
    no rootfs signature at 00286000!
    no rootfs signature at 00287000!
    no rootfs signature at 00288000!
    no rootfs signature at 00289000!
    no rootfs signature at 0028A000!
    no rootfs signature at 0028B000!
    no rootfs signature at 0028C000!
    no rootfs signature at 0028D000!
    no rootfs signature at 0028E000!
    no rootfs signature at 0028F000!
    no rootfs signature at 00290000!
    no rootfs signature at 00291000!
    no rootfs signature at 00292000!
    no rootfs signature at 00293000!
    no rootfs signature at 00294000!
    no rootfs signature at 00295000!
    no rootfs signature at 00296000!
    no rootfs signature at 00297000!
    no rootfs signature at 00298000!
    no rootfs signature at 00299000!
    no rootfs signature at 0029A000!
    no rootfs signature at 0029B000!
    no rootfs signature at 0029C000!
    no rootfs signature at 0029D000!
    no rootfs signature at 0029E000!
    no rootfs signature at 0029F000!
    no rootfs signature at 002A0000!
    no rootfs signature at 002A1000!
    no rootfs signature at 002A2000!
    no rootfs signature at 002A3000!
    no rootfs signature at 002A4000!
    no rootfs signature at 002A5000!
    no rootfs signature at 002A6000!
    no rootfs signature at 002A7000!
    no rootfs signature at 002A8000!
    no rootfs signature at 002A9000!
    no rootfs signature at 002AA000!
    no rootfs signature at 002AB000!
    no rootfs signature at 002AC000!
    no rootfs signature at 002AD000!
    no rootfs signature at 002AE000!
    no rootfs signature at 002AF000!
    no rootfs signature at 002B0000!
    no rootfs signature at 002B1000!
    no rootfs signature at 002B2000!
    no rootfs signature at 002B3000!
    no rootfs signature at 002B4000!
    no rootfs signature at 002B5000!
    no rootfs signature at 002B6000!
    no rootfs signature at 002B7000!
    no rootfs signature at 002B8000!
    no rootfs signature at 002B9000!
    no rootfs signature at 002BA000!
    no rootfs signature at 002BB000!
    no rootfs signature at 002BC000!
    no rootfs signature at 002BD000!
    no rootfs signature at 002BE000!
    no rootfs signature at 002BF000!
    no rootfs signature at 002C0000!
    no rootfs signature at 002C1000!
    no rootfs signature at 002C2000!
    no rootfs signature at 002C3000!
    no rootfs signature at 002C4000!
    no rootfs signature at 002C5000!
    no rootfs signature at 002C6000!
    no rootfs signature at 002C7000!
    no rootfs signature at 002C8000!
    no rootfs signature at 002C9000!
    no rootfs signature at 002CA000!
    no rootfs signature at 002CB000!
    no rootfs signature at 002CC000!
    no rootfs signature at 002CD000!
    no rootfs signature at 002CE000!
    no rootfs signature at 002CF000!
    no rootfs signature at 002D0000!
    no rootfs signature at 002D1000!
    no rootfs signature at 002D2000!
    no rootfs signature at 002D3000!
    no rootfs signature at 002D4000!
    no rootfs signature at 002D5000!
    no rootfs signature at 002D6000!
    no rootfs signature at 002D7000!
    no rootfs signature at 002D8000!
    no rootfs signature at 002D9000!
    no rootfs signature at 002DA000!
    no rootfs signature at 002DB000!
    no rootfs signature at 002DC000!
    no rootfs signature at 002DD000!
    no rootfs signature at 002DE000!
    no rootfs signature at 002DF000!
    no rootfs signature at 002E0000!
    no rootfs signature at 002E1000!
    no rootfs signature at 002E2000!
    no rootfs signature at 002E3000!
    no rootfs signature at 002E4000!
    no rootfs signature at 002E5000!
    no rootfs signature at 002E6000!
    no rootfs signature at 002E7000!
    no rootfs signature at 002E8000!
    no rootfs signature at 002E9000!
    no rootfs signature at 002EA000!
    no rootfs signature at 002EB000!
    no rootfs signature at 002EC000!
    no rootfs signature at 002ED000!
    no rootfs signature at 002EE000!
    no rootfs signature at 002EF000!
    no rootfs signature at 002F0000!
    no rootfs signature at 002F1000!
    no rootfs signature at 002F2000!
    no rootfs signature at 002F3000!
    no rootfs signature at 002F4000!
    no rootfs signature at 002F5000!
    no rootfs signature at 002F6000!
    no rootfs signature at 002F7000!
    no rootfs signature at 002F8000!
    no rootfs signature at 002F9000!
    no rootfs signature at 002FA000!
    no rootfs signature at 002FB000!
    no rootfs signature at 002FC000!
    no rootfs signature at 002FD000!
    no rootfs signature at 002FE000!
    no rootfs signature at 002FF000!
    no rootfs signature at 00300000!
    no rootfs signature at 00301000!
    no rootfs signature at 00302000!
    no rootfs signature at 00303000!
    no rootfs signature at 00304000!
    no rootfs signature at 00305000!
    no rootfs signature at 00306000!
    no rootfs signature at 00307000!
    no rootfs signature at 00308000!
    no rootfs signature at 00309000!
    no rootfs signature at 0030A000!
    no rootfs signature at 0030B000!
    no rootfs signature at 0030C000!
    no rootfs signature at 0030D000!
    no rootfs signature at 0030E000!
    no rootfs signature at 0030F000!
    no rootfs signature at 00310000!
    no rootfs signature at 00311000!
    no rootfs signature at 00312000!
    no rootfs signature at 00313000!
    no rootfs signature at 00314000!
    no rootfs signature at 00315000!
    no rootfs signature at 00316000!
    no rootfs signature at 00317000!
    no rootfs signature at 00318000!
    no rootfs signature at 00319000!
    no rootfs signature at 0031A000!
    no rootfs signature at 0031B000!
    no rootfs signature at 0031C000!
    no rootfs signature at 0031D000!
    no rootfs signature at 0031E000!
    no rootfs signature at 0031F000!
    no rootfs signature at 00320000!
    no rootfs signature at 00321000!
    no rootfs signature at 00322000!
    no rootfs signature at 00323000!
    no rootfs signature at 00324000!
    no rootfs signature at 00325000!
    no rootfs signature at 00326000!
    no rootfs signature at 00327000!
    no rootfs signature at 00328000!
    no rootfs signature at 00329000!
    no rootfs signature at 0032A000!
    no rootfs signature at 0032B000!
    no rootfs signature at 0032C000!
    no rootfs signature at 0032D000!
    no rootfs signature at 0032E000!
    no rootfs signature at 0032F000!
    no rootfs signature at 00330000!
    no rootfs signature at 00331000!
    no rootfs signature at 00332000!
    no rootfs signature at 00333000!
    no rootfs signature at 00334000!
    no rootfs signature at 00335000!
    no rootfs signature at 00336000!
    no rootfs signature at 00337000!
    no rootfs signature at 00338000!
    no rootfs signature at 00339000!
    no rootfs signature at 0033A000!
    no rootfs signature at 0033B000!
    no rootfs signature at 0033C000!
    no rootfs signature at 0033D000!
    no rootfs signature at 0033E000!
    no rootfs signature at 0033F000!
    no rootfs signature at 00340000!
    no rootfs signature at 00341000!
    no rootfs signature at 00342000!
    no rootfs signature at 00343000!
    no rootfs signature at 00344000!
    no rootfs signature at 00345000!
    no rootfs signature at 00346000!
    no rootfs signature at 00347000!
    no rootfs signature at 00348000!
    no rootfs signature at 00349000!
    no rootfs signature at 0034A000!
    no rootfs signature at 0034B000!
    no rootfs signature at 0034C000!
    no rootfs signature at 0034D000!
    no rootfs signature at 0034E000!
    no rootfs signature at 0034F000!
    no rootfs signature at 00350000!
    no rootfs signature at 00351000!
    no rootfs signature at 00352000!
    no rootfs signature at 00353000!
    no rootfs signature at 00354000!
    no rootfs signature at 00355000!
    no rootfs signature at 00356000!
    no rootfs signature at 00357000!
    no rootfs signature at 00358000!
    no rootfs signature at 00359000!
    no rootfs signature at 0035A000!
    no rootfs signature at 0035B000!
    no rootfs signature at 0035C000!
    no rootfs signature at 0035D000!
    no rootfs signature at 0035E000!
    no rootfs signature at 0035F000!
    no rootfs signature at 00360000!
    no rootfs signature at 00361000!
    no rootfs signature at 00362000!
    no rootfs signature at 00363000!
    no rootfs signature at 00364000!
    no rootfs signature at 00365000!
    no rootfs signature at 00366000!
    no rootfs signature at 00367000!
    no rootfs signature at 00368000!
    no rootfs signature at 00369000!
    no rootfs signature at 0036A000!
    no rootfs signature at 0036B000!
    no rootfs signature at 0036C000!
    no rootfs signature at 0036D000!
    no rootfs signature at 0036E000!
    no rootfs signature at 0036F000!
    no rootfs signature at 00370000!
    no rootfs signature at 00371000!
    no rootfs signature at 00372000!
    no rootfs signature at 00373000!
    no rootfs signature at 00374000!
    no rootfs signature at 00375000!
    no rootfs signature at 00376000!
    no rootfs signature at 00377000!
    no rootfs signature at 00378000!
    no rootfs signature at 00379000!
    no rootfs signature at 0037A000!
    no rootfs signature at 0037B000!
    no rootfs signature at 0037C000!
    no rootfs signature at 0037D000!
    no rootfs signature at 0037E000!
    no rootfs signature at 0037F000!
    no rootfs signature at 00380000!
    no rootfs signature at 00381000!
    no rootfs signature at 00382000!
    no rootfs signature at 00383000!
    no rootfs signature at 00384000!
    no rootfs signature at 00385000!
    no rootfs signature at 00386000!
    no rootfs signature at 00387000!
    no rootfs signature at 00388000!
    no rootfs signature at 00389000!
    no rootfs signature at 0038A000!
    no rootfs signature at 0038B000!
    no rootfs signature at 0038C000!
    no rootfs signature at 0038D000!
    no rootfs signature at 0038E000!
    no rootfs signature at 0038F000!
    no rootfs signature at 00390000!
    no rootfs signature at 00391000!
    no rootfs signature at 00392000!
    no rootfs signature at 00393000!
    no rootfs signature at 00394000!
    no rootfs signature at 00395000!
    no rootfs signature at 00396000!
    no rootfs signature at 00397000!
    no rootfs signature at 00398000!
    no rootfs signature at 00399000!
    no rootfs signature at 0039A000!
    no rootfs signature at 0039B000!
    no rootfs signature at 0039C000!
    no rootfs signature at 0039D000!
    no rootfs signature at 0039E000!
    no rootfs signature at 0039F000!
    no rootfs signature at 003A0000!
    no rootfs signature at 003A1000!
    no rootfs signature at 003A2000!
    no rootfs signature at 003A3000!
    no rootfs signature at 003A4000!
    no rootfs signature at 003A5000!
    no rootfs signature at 003A6000!
    no rootfs signature at 003A7000!
    no rootfs signature at 003A8000!
    no rootfs signature at 003A9000!
    no rootfs signature at 003AA000!
    no rootfs signature at 003AB000!
    no rootfs signature at 003AC000!
    no rootfs signature at 003AD000!
    no rootfs signature at 003AE000!
    no rootfs signature at 003AF000!
    no rootfs signature at 003B0000!
    no rootfs signature at 003B1000!
    no rootfs signature at 003B2000!
    no rootfs signature at 003B3000!
    no rootfs signature at 003B4000!
    no rootfs signature at 003B5000!
    no rootfs signature at 003B6000!
    no rootfs signature at 003B7000!
    no rootfs signature at 003B8000!
    no rootfs signature at 003B9000!
    no rootfs signature at 003BA000!
    no rootfs signature at 003BB000!
    no rootfs signature at 003BC000!
    no rootfs signature at 003BD000!
    no rootfs signature at 003BE000!
    no rootfs signature at 003BF000!
    no rootfs signature at 003C0000!
    no rootfs signature at 003C1000!
    no rootfs signature at 003C2000!
    no rootfs signature at 003C3000!
    no rootfs signature at 003C4000!
    no rootfs signature at 003C5000!
    no rootfs signature at 003C6000!
    no rootfs signature at 003C7000!
    no rootfs signature at 003C8000!
    no rootfs signature at 003C9000!
    no rootfs signature at 003CA000!
    no rootfs signature at 003CB000!
    no rootfs signature at 003CC000!
    no rootfs signature at 003CD000!
    no rootfs signature at 003CE000!
    no rootfs signature at 003CF000!
    no rootfs signature at 003D0000!
    no rootfs signature at 003D1000!
    no rootfs signature at 003D2000!
    no rootfs signature at 003D3000!
    no rootfs signature at 003D4000!
    no rootfs signature at 003D5000!
    no rootfs signature at 003D6000!
    no rootfs signature at 003D7000!
    no rootfs signature at 003D8000!
    no rootfs signature at 003D9000!
    no rootfs signature at 003DA000!
    no rootfs signature at 003DB000!
    no rootfs signature at 003DC000!
    no rootfs signature at 003DD000!
    no rootfs signature at 003DE000!
    no rootfs signature at 003DF000!
    no rootfs signature at 003E0000!
    no rootfs signature at 003E1000!
    no rootfs signature at 003E2000!
    no rootfs signature at 003E3000!
    no rootfs signature at 003E4000!
    no rootfs signature at 003E5000!
    no rootfs signature at 003E6000!
    no rootfs signature at 003E7000!
    no rootfs signature at 003E8000!
    no rootfs signature at 003E9000!
    no rootfs signature at 003EA000!
    no rootfs signature at 003EB000!
    no rootfs signature at 003EC000!
    no rootfs signature at 003ED000!
    no rootfs signature at 003EE000!
    no rootfs signature at 003EF000!
    no rootfs signature at 003F0000!
    no rootfs signature at 003F1000!
    no rootfs signature at 003F2000!
    no rootfs signature at 003F3000!
    no rootfs signature at 003F4000!
    no rootfs signature at 003F5000!
    no rootfs signature at 003F6000!
    no rootfs signature at 003F7000!
    no rootfs signature at 003F8000!
    no rootfs signature at 003F9000!
    no rootfs signature at 003FA000!
    no rootfs signature at 003FB000!
    no rootfs signature at 003FC000!
    no rootfs signature at 003FD000!
    no rootfs signature at 003FE000!
    no rootfs signature at 003FF000!
    no rootfs signature at 00400000!
    P0phymode=01, embedded phy
    
    ---Ethernet init Okay!
    tuya:start receive production test frame ...
    P0phymode=01, embedded phy
    
    ---Ethernet init Okay!
    <RealTek>

**Comment by ersinpw** [comment]
Solved! Used new usb to serial chip and now it works. TX wasn't working properly

**Comment by parasite85** [comment]
I glad to hear that reset glitch technique is working.
